# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MtspSolver
                                 A QGIS plugin
 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-02-16
        copyright            : (C) 2022 by Boris Karpov
        email                : bkarpov96@ya.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Boris Karpov'
__date__ = '2022-02-16'
__copyright__ = '(C) 2022 by Boris Karpov'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MtspSolver class from file MtspSolver.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mtsp import MtspRoutingPlugin
    return MtspRoutingPlugin()
