# -*- coding: utf-8 -*-

"""
/***************************************************************************
 MtspSolver
                                 A QGIS plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-02-16
        copyright            : (C) 2022 by Boris Karpov
        email                : bkarpov96@ya.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Boris Karpov'
__date__ = '2022-02-16'
__copyright__ = '(C) 2022 by Boris Karpov'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis import core
from qgis.PyQt import QtCore

from routing import _solution as sl
from routing import _spatial_objects as sp


class MtspSolverAlgorithm(core.QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    DEST_LAYER = "DEST_LAYER"
    ROADS_LAYER = "ROADS_LAYER"
    NUMBER_OF_ROUTES = "NUMBER_OF_ROUTES"
    RESULT = "RESULT"

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            core.QgsProcessingParameterFeatureSource(
                self.DEST_LAYER,
                self.tr("Destinations"),
                [core.QgsProcessing.TypeVectorPoint]
            )
        )

        self.addParameter(
            core.QgsProcessingParameterFeatureSource(
                self.ROADS_LAYER,
                self.tr("Roads"),
                [core.QgsProcessing.TypeVectorLine]
            )
        )

        self.addParameter(
            core.QgsProcessingParameterNumber(
                self.NUMBER_OF_ROUTES,
                self.tr("Number of routes"),
                minValue=1,
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, source.fields(), source.wkbType(), source.sourceCrs())

        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()

        for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break

            # Add a feature in the sink
            sink.addFeature(feature, QgsFeatureSink.FastInsert)

            # Update the progress bar
            feedback.setProgress(int(current * total))

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {self.OUTPUT: dest_id}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return "Build routes"

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return "Routing"

    def tr(self, string):
        return QtCore.QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return MtspSolverAlgorithm()

    def shortHelpString(self):
        return self.tr("""
        Solve the multiple traveling salesman problem (MTSP).
        Divide the points into clusters of the same size and build routes in them.

        Parameters:
            Destinations: Layer with destinations. All points must be reachable by roads.
            Roads: Layer with roads. It's strongly recommended to divide roads by roads before running the algorithm.
            Number of routes: Number of routes to build.
        """)
